### ISSUE TITLE
Feature Request: High contrast edition of the theme.

### ISSUE THREAD

**Issue by halfo** [adamsome/vscode-theme-gruvbox-minor#1]
Thanks for this awesome theme. It would be nice if there's an high contrast edition of the theme where the panes will have some sort of border or they have slightly different background color. Then it would be easier to distinguish among panes. Some folk like me prefer this than the whole workbench being in same flat color.

**Comment by adamsome** [comment]
It's not quite a high contrast mode, but the theme has been updated to add borders between editors and the sidebar.
