### ISSUE TITLE
Very low contrast for highlighted text in search box

### ISSUE THREAD

**Issue by mrtzd** [adamsome/vscode-theme-gruvbox-minor#11]
The text is barely legible if you highlight text in the search box.

![image](https://user-images.githubusercontent.com/82378750/164714550-6429ebbd-d583-43f3-84f7-735a334410d8.png)

**Comment by adamsome** [comment]
Fix in v2.7.1:

Decrease selection background opacity

Fix issue where selected non-editor (e.g. text inputs)
text was illegible.
