### ISSUE TITLE
Fix stickyscroll border

### ISSUE THREAD

**Issue by basepi** [adamsome/vscode-theme-gruvbox-minor#12]
Love the theme! However, it doesn't properly color the border when using

```
    "editor.stickyScroll.enabled": true,
```

Here's a screenshot from Tom Philbin's Gruvbox Themes (light medium):

![image](https://user-images.githubusercontent.com/702318/199282961-e616c59a-da6e-4239-8d27-e040293bd1c5.png)

And here's a screenshot from gruvbox-minor (light medium):

![image](https://user-images.githubusercontent.com/702318/199283211-eb223601-6027-49b9-92b4-244c096407e9.png)

Notice the lack of border in the second screenshot.

Is this an easy fix? I have no experience with theming vscode. 😅

**Comment by basepi** [comment]
Actually, the better place to fix this would probably be `editorStickyScroll.background`, which I found out about here: https://github.com/microsoft/vscode/issues/157185#issuecomment-1211988093

For now I'll just use colorCustomizations but figured I'd leave this issue open because I think it would be an improvement. I ended up adding three color customizations that I think really improve the "edges" between different pieces of the sidebar. I basically used the "soft light" background color, so it's distinguished from the "medium light" background color everywhere else:

```json
  "workbench.colorCustomizations": {
    "[Gruvbox Minor Light Medium]": {
      "editorStickyScroll.background": "#f2e5bc",
      "sideBarSectionHeader.background": "#f2e5bc",
      "activityBar.background": "#f2e5bc"
    },
    "editorRuler.foreground": "#f2e5bc"
  },
```

Here's a screenshot with these changes:

![image](https://user-images.githubusercontent.com/702318/199536421-bb294a03-d342-4d8c-aee0-5d9c152d7140.png)

And without:

![image](https://user-images.githubusercontent.com/702318/199536655-8f82e57e-8cdc-41d7-8a3b-21e928d2481c.png)

Now that I know what these color controls are called, I may make a PR. I would just need to find good color changes for the `soft` and `hard` versions for consistency, I suppose.

**Comment by adamsome** [comment]
Appreciate your feedback and looking into options!

As you mentioned, the sticky scroll currently allows theming the background color (`editorStickyScroll.background`) and uses the scrollbar shadow (`scrollbar.shadow`) as its bottom "border". A proper sticky scroll border theme term may be added to VS Code team's backlog according to this [thread](https://github.com/microsoft/vscode/issues/157185).

In the meantime, I'll update the theme to have the sticky scroll section have a different background color from the main editor background and revisit once the border itself can be themed.

**Comment by adamsome** [comment]
Added sticky scroll background color in v2.7.2.
