### ISSUE TITLE
Neovim port? 

### ISSUE THREAD

**Issue by lindelleric** [adamsome/vscode-theme-gruvbox-minor#18]
This is easily the best color scheme I've used! 

I've been trying to find something equivalent for neovim, but nothing really fits the bill quite like this one. 

I'm reluctant to trying to port this myself, even though I'm considering it. 

Do you know of any projects who've tried it?

**Comment by adamsome** [comment]
This theme is ported from the [original Gruvbox vim theme](https://github.com/morhetz/gruvbox), which I fell in love with when using vim. I have made a number of customizations and deviations for this VSCode theme from the original for some languages, especially Javascript/Typescript, though, which I sometimes miss when using vim.

There's also [this Gruvbox nvim theme](https://github.com/ellisonleao/gruvbox.nvim) which I've used as well, but again has a number of differences.

Those are the ones I know of and used!
