### ISSUE TITLE
feature request: opaque tooltip background

### ISSUE THREAD

**Issue by jrr** [adamsome/vscode-theme-gruvbox-minor#4]
It can be difficult to read a typescript mouseover when there's text behind it. Can the background be made opaque? I'm willing to take a stab at it if you can point me in the right direction.

**Comment by MarkBorcherding** [comment]
I agree. The transparent background is really hard to read. Here is how I fixed it.

```json
 {
   "workbench.colorCustomizations": {
        "editorHoverWidget.background": "#3c3836"
    },
}
```

**Comment by adamsome** [comment]
Pushed to v2.2.2.
