### ISSUE TITLE
Overlapping backgrounds in diff editor

### ISSUE THREAD

**Issue by chelmich** [adamsome/vscode-theme-gruvbox-minor#6]
The background for consecutive inserted and removed lines overlaps. See the below screenshot. Also now that I look at it, the color of the line numbers is pretty hard to read.
![image](https://user-images.githubusercontent.com/10083027/89000149-da335e80-d2b3-11ea-80b6-d1a3727881b1.png)
For reference, here's the expected behavior from the default theme:
![image](https://user-images.githubusercontent.com/10083027/89000226-0cdd5700-d2b4-11ea-9951-c8b6823b0dd1.png)
I poked around a bit with the inspect element tool but I couldn't find anything obvious. Not sure what's causing this, but also I don't really have any experience with typescript, etc.

**Comment by adamsome** [comment]
Fixed in 2.7.0.
